on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files Laravel
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 154.41.240.225
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /../laravel_yhs_data/
        exclude: public/**
          - public/
          - .git*
          - .git*/**
          -  **/.git*/**
          - node_modules/**
          - node_modules/**/*
        
    - name: 📂 Sync files public
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 154.41.240.225
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./public/
        server-dir: /../public_html/
        exclude: .htaccess
          - credentials.json
          - favicon.ico
          - index.php
          - robots.txt
          - web.config